github:
  org: kkday-it

repos:
  - name: b2c-web
    githubRepo: kkday-b2c-web
    label: b2c-web
    path: ~/KKday/kkday-b2c-web
  - name: member-ci
    githubRepo: kkday-member-ci
    label: member-ci
    path: ~/KKday/kkday-member-ci
  - name: mobile-member-ci
    githubRepo: kkday-mobile-member-ci
    label: mobile-member-ci
    path: ~/KKday/kkday-mobile-member-ci
  - name: design-system
    githubRepo: web-design-system
    label: DesignSystem
    path: ~/KKday/web-design-system

claude:
  cliPath: auto
